### ISSUE TITLE
When will devices be available again

### ISSUE THREAD

**Issue by jwich71** [lambdamikel/Talker-80#1]
Hi, my name is Jürgen from Germany and I'm very interested in an Talker-80 for my pretty nice TRS-80 Model 1 (https://homecomputerguy.de/en/2021/05/05/tandy-trs-80-model-i-level-ii-2/#more-1434).
Can I buy one somehow?
I plan to visit the Classic Computing 2021 as an exhibitor (https://www.classic-computing.org/cc2021/) and it would be great to demonstrate the voice synthesizer with the ELIZA software on my TRS-80 there.
Hope you can help me out?

Kind regards.

**Comment by jwich71** [comment]
Huhu ... someone here?

**Comment by lambdamikel** [comment]
Hi Jürgen - sorry, I never got a notification from this one (I guess this landed in Spam). Sure, I can assemble one - please send a mail to miacwess@gmail.com! 
Cheers
Michael

**Comment by jwich71** [comment]
Hi Michael. Doesn't matter. I sent you a mail in the meantime. 
Thank you for your help.
